config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/create'

  get 'comments/new'

  get 'comments/edit'

  get 'comments/show'

  get 'comments/update'

  get 'comments/destroy'

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get 'video' => 'video#index'

  get 'posts/index'

  get 'posts/create'

  get 'posts/new'

  get 'posts/edit'

  get 'posts/show'

  get 'posts/update'

  get 'posts/destroy'

  get 'tags/index'

  get 'tags/create'

  get 'tags/new'

  get 'tags/edit'

  get 'tags/show'

  get 'tags/update'

  get 'tags/destroy'

  get 'tags/index'

  get 'tags/create'

  get 'tags/new'

  get 'tags/edit'

  get 'tags/show'

  get 'tags/update'

  get 'tags/destroy'

  root 'posts#index'
  get 'about' => 'main#about'
  
  resources :posts do
    resources :comments
  end
  resources :comments
  resources :tags

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
		has_and_belongs_to_many :tags
		has_many :comment
end

app/models/posts_tags.rb
class PostsTags < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
		validates :email, 
	presence: true,
  uniqueness: {case_sensitive: false}

  validates :password, presence: true, on: :create

  has_secure_password
  has_many :post
 
  def self.authenticate email, password
    User.find_by_email(email).try(:authenticate, password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
      @comments = Comment.all
      @comment = Comment.new
  end

  def create
    comment = Comment.create comment_params do |c|
      c.save
    end
    redirect_to :back
  end

  def new
      @comment = Comment.new
  end

  def edit
    @comment = Comment.find params[:id]
    session[:return_to] ||= request.referer
  end

  def show
    @comment = Comment.find params[:id]
    @posts = @comment.posts
  end

  def update
    t = Comment.find params[:id]
    t.update comment_params
    redirect_to session.delete(:return_to)
  end

  def destroy
    Comment.find(params[:id]).delete
    redirect_to :back
  end


  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
      @posts = Post.all
  end

  def create
    post = Post.create(post_params)
    redirect_to posts_path post
  end

  def new
      @post = Post.new
      @tags = Tag.all
  end

  def edit
    @post = Post.find params[:id]
    @tags = Tag.all
  end

  def show
    @post = Post.find params[:id]
    @comments = Comment.all
  end

  def update
    p = Post.find params[:id]
    p.update post_params
    redirect_to posts_path
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:id, :description, :title, :picture, tag_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.authenticate user_params[:email], user_params[:password]

  	if @user
  		session[:user_id] = @user.id
  		flash[:success] = "User logged in!"
  		redirect_to root_path
  	else
  		flash[:danger] = "Credentials Invalid!"
  		redirect_to login_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	flash[:success] = "User logged out!!"
  	redirect_to root_path
  end

  private

  def user_params
  	params.require(:user).permit(:email, :password)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
      @tags = Tag.all
  end

  def create
    tag = Tag.create(tag_params)
    redirect_to tags_path tag
  end

  def new
      @tag = Tag.new
  end

  def edit
    @tag = Tag.find params[:id]
  end

  def show
    @tag = Tag.find params[:id]
    @posts = @tag.posts
  end

  def update
    t = Tag.find params[:id]
    t.update tag_params
    redirect_to tags_path
  end

  def destroy
    Tag.find(params[:id]).destroy
    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/comments/_create.html.erb
<%= bootstrap_form_for Comment.new, url: post_comments_path(@post, Comment.new), html: { method: :post } do |c| %>
  <%= c.text_area :content %>
  <%= c.hidden_field :post_id, value: @post.id %>
  <%= c.primary %>
<% end %>

app/views/comments/_show.html.erb
<div class="comment">
	<h3>Comments</h3><hr>
		<% @comments.each do |comment| %>
		    <ul>
			    <li>
				    <h4><%= comment.content %></h4>
				    <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
				    <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete %>
				 </li>
		    </ul>
		    <hr>
		<% end %>
</div>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= bootstrap_form_for [@post, @comment] do |f| %>
	<div>
		<%= f.text_field :content %>
	</div>
	<%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/creatures/new.html.erb
<h1>Creature Creator</h1>
<!-- <p>Find me in app/views/creatures/new.html.erb</p>
 -->

<%= form_for @creature do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	
	<div>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
		<%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Help Me Already</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
		<ul class="nav nav-pills">
		  <li role="presentation"><a href="<%= posts_path %>">Posts</a></li>
		  <li role="presentation"><a href="<%= tags_path %>">Tags</a></li>
		  <li role="presentation"><a href="<%= new_post_path %>">New Post</a></li>
		  <li role="presentation"><a href="<%= new_tag_path %>">New Tag</a></li>
		  <li role="presentation"><a href="<%= video_path %>">Video Chat</a></li>
		</ul>


<%= yield %>

</body>
</html>

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Post Edit</h1>

<%= bootstrap_form_for(@post)  do |f| %>
	<div>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.text_field :picture %>
	</div>
	<div>
		<%= f.text_area :description %>
	</div>

	<%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>

	<%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div class="container-fluid">
	<% @posts.each do |post| %>
	<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
				<img src="<%= post.picture %>">
			</div>
			<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
				<h2><%= link_to post.title, post_path(post) %></h2>
				<p><%= post.description %></p>
				<ul>
				<% for tag in post.tags %>
					<li> <%= link_to tag.name, tag_path(tag) %></li>
				<% end %>
				</ul>

			   <%= link_to 'Edit', edit_post_path(post) %>
				<%= link_to 'Delete', post, method: :delete %>
				</div>
			</div>
	<% end %>
	</div>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<%= form_for @post do |f| %>
	<div>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label :picture %>
		<%= f.text_field :picture %>
	</div>
	
	<div>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
		<%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
	<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
			<img src="<%= @post.picture %>">
		</div>
		<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
			<h2><%= @post.title%></h2>
			<p><%= @post.description %></p>
		</div>
	</div>
</div>
			<%= render 'comments/show' %>
        <%= render 'comments/create' %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<h1>Tag edit</h1>


<%= form_for @tag do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<%= f.submit %>
<% end %>

app/views/tags/index.html.erb
<h1>Tags</h1>
<% @tags.each do |tag| %>
	<h2><%= tag.name %></h2>
   <%= link_to 'Edit', edit_tag_path(tag) %>
	<%= link_to 'Delete', tag, method: :delete %>
<% end %>

app/views/tags/new.html.erb
<h1>Create Tag</h1>

<%= form_for @tag do |f| %>
	<div>
		<%= f.text_field :name %>
	</div>
	<%= f.submit %>
<% end %>

app/views/tags/show.html.erb
<h1>Posts with <%= @tag.name %> Tag</h1>


<% for post in @posts %>
		<li> <%= link_to post.title, post_path(post) %>
</li>
	<% end %>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>

app/views/video/index.html.erb
  <title>PeerJS - Video chat example</title>
  <link rel="stylesheet" href="/style.css">
  <script src="video.js"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/peerjs/0.3.14/peer.js"></script>
  <script>

    // Compatibility shim
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;

    //linked to web server to receive call instance id
    var peer = new Peer({host:'https://p2ppeerjs.herokuapp.com', port: 443, key: 'peerjs', secure: true});

    //shows the user's call id
    peer.on('open', function(){
      $('#my-id').text(peer.id);
    });

    // Receiving a call
    peer.on('call', function(call){
      // Answer the call automatically (instead of prompting user) for
      call.answer(window.localStream);
      step3(call);
    });
    peer.on('error', function(err){
      alert(err.message);
      // Return to step 2 if error occurs
      step2();
    });

    // Click handlers setup
    $(function(){
      $('#make-call').click(function(){
        // Initiate a call!
        var call = peer.call($('#callto-id').val(), window.localStream);

        step3(call);
      });

      $('#end-call').click(function(){
        window.existingCall.close();
        step2();
      });

      // Retry if getUserMedia fails
      $('#step1-retry').click(function(){
        $('#step1-error').hide();
        step1();
      });

      // Get things started
      step1();
    });

    function step1 () {
      // Get audio/video stream
      navigator.getUserMedia({audio: true, video: true}, function(stream){
        // Set your video displays
        $('#my-video').prop('src', URL.createObjectURL(stream));

        window.localStream = stream;
        step2();
      }, function(){ $('#step1-error').show(); });
    }

    function step2 () {
      $('#step1, #step3').hide();
      $('#step2').show();
    }

    function step3 (call) {
      // Hang up on an existing call if present
      if (window.existingCall) {
        window.existingCall.close();
      }

      // Wait for stream on the call, then set peer video display
      call.on('stream', function(stream){
        $('#their-video').prop('src', URL.createObjectURL(stream));
      });

      // UI stuff
      window.existingCall = call;
      $('#their-id').text(call.peer);
      call.on('close', step2);
      $('#step1, #step2').hide();
      $('#step3').show();
    }

  </script>

  <div class="pure-g">

      <!-- Video area -->
      <div class="pure-u-2-3" id="video-container">
        <video id="their-video" autoplay></video>
        <video id="my-video" muted="true" autoplay></video>
      </div>

      <!-- Steps -->
      <div class="pure-u-1-3">
        <h2>PeerJS Video Chat</h2>

        <!-- Get local audio/video stream -->
        <div id="step1">
          <p>Please click 'allow' on the top of the screen so we can access your webcam and microphone for calls.</p>
          <div id="step1-error">
            <p>Failed to access the webcam and microphone. Make sure to run this site on an https server and click allow when asked for permission by the browser.</p>
            <a href="<%= video_path %>" class="pure-button pure-button-error" id="step1-retry">Try again</a>
          </div>
        </div>

        <!-- Make calls to others -->
        <div id="step2">
          <p>Your id: <span id="my-id">...</span></p>
          <p>Share this id with others so they can call you.</p>
          <h3>Make a call</h3>
          <div class="form">
            <input type="text" placeholder="Call user id..." id="callto-id">
            <a href="#" class="pure-button pure-button-success" id="make-call">Call</a>
          </div>
        </div>

        <!-- Call in progress -->
        <div id="step3">
          <p>Currently in call with <span id="their-id">...</span></p>
          <p><a href="#" class="pure-button pure-button-error" id="end-call">End call</a></p>
        </div>
      </div>
  </div>